name: CD - Formativa
on:
  push:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: finalproject
          path: |
            **.py
            README.md
            
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: finalproject
      - name: Display files
        run: ls -R