name: CI - Formativa
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  test:
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

  alert:
    runs-on: windows-latest
    steps:
      - name: Send Telegram Alert
        env:
          TELEGRAM_TOKEN: '7082971552:AAGbOG6amP--nccNR9Oxpr4cdJylx-3f2zU'
          TELEGRAM_CHAT_ID: '-4245329360'
        shell: pwsh
        run: |
          $url = "https://api.telegram.org/bot${env:TELEGRAM_TOKEN}/sendMessage"
          $body = @{
            chat_id = "${env:TELEGRAM_CHAT_ID}"
            text = " --------NOTIFICACAO ENVIADA---------"
          } | ConvertTo-Json
          Invoke-RestMethod -Uri $url -Method Post -Body $body -ContentType "application/json"
